facet.widget.config.degov_date_range_picker:
  type: facet.widget.default_config
  mapping:
    display_relative:
      label: "Date display"
      type: integer
    granularity:
      label: "Granularity"
      type: integer
    date_display:
      label: "Date format"
      type: string

facet.widget.config.tags:
  type: facet.widget.config.dropdown
  label: 'Tags widget configuration'

facet.widget.config.content_bundle:
  type: facet.widget.config.dropdown
  label: 'Content bundles widget configuration'
