dependencies:
  config:
    - field.field.media.facts.field_topic
content:
  field_topic:
    weight: 0
    label: hidden
    settings:
      link: false
    third_party_settings: {  }
    type: entity_reference_label
    region: content
