# Schema for the configuration files of the styled_google_map module

styled_google_map.settings:
  type: config_object
  label: 'Styled Google Map settings'
  mapping:
    styled_google_map_google_auth_method:
      type: integer
      label: 'Google API Authentication Method'
    styled_google_map_google_apikey:
      type: string
      label: 'Google Maps API Key'
    styled_google_map_google_client_id:
      type: string
      label: 'Google Maps API for Work: Client ID'
