field_tags_target_id:
  id: field_tags_target_id
  table: node__field_tags
  field: field_tags_target_id
  relationship: none
  group_type: group
  admin_label: ''
  operator: or
  value: {  }
  group: 1
  exposed: true
  expose:
    operator_id: field_tags_target_id_op
    label: Tags
    description: ''
    use_operator: false
    operator: field_tags_target_id_op
    identifier: field_tags_target_id
    required: false
    remember: false
    multiple: false
    remember_roles:
      authenticated: authenticated
      anonymous: '0'
      administrator: '0'
      manager: '0'
      editor: '0'
      usermanager: '0'
      system_configurator: '0'
    reduce: false
  is_grouped: false
  group_info:
    label: ''
    description: ''
    identifier: ''
    optional: true
    widget: select
    multiple: false
    remember: false
    default_group: All
    default_group_multiple: {  }
    group_items: {  }
  reduce_duplicates: false
  type: textfield
  limit: true
  vid: tags
  hierarchy: false
  error_message: true
  plugin_id: taxonomy_index_tid
