services:
  degov_config_integrity.module_integrity_checker:
    class: Drupal\degov_config_integrity\DegovModuleIntegrityChecker
    arguments: ['@module_handler', '@config.factory', '@file_system']
