config_rewrite: replace
langcode: en
status: true
dependencies:
  enforced:
    module:
      - degov_metatags
id: global
label: Global
tags:
  title: '[current-page:title] | [site:name]'
  dcterms_description: '[node:field_teaser_text]'
  dcterms_title: '[node:field_teaser_title]'
  og_description: '[node:field_teaser_text]'
  og_image: '[node:field_teaser_image:entity:image:crop_1_to_1]'
  og_title: '[node:field_teaser_title]'
  twitter_cards_description: '[node:field_teaser_text]'
  twitter_cards_image: '[node:field_teaser_image:entity:image:crop_1_to_1]'
  twitter_cards_title: '[node:field_teaser_title]'
  twitter_cards_type: summary
