third_party_settings:
  field_group:
    group_common:
      children:
        - field_topic
        - field_content_type
        - field_view_control
content:
  field_content_type:
    weight: 10
    settings: {  }
    third_party_settings: {  }
    type: options_select
    region: content
  field_topic:
    weight: 9
    settings: {  }
    third_party_settings: {  }
    type: options_select
    region: content
  field_view_control:
    weight: 11
    settings: {  }
    third_party_settings: {  }
    type: options_select
    region: content
