field_event_date_end_value:
  id: field_event_date_end_value
  table: node__field_event_date_end
  field: field_event_date_end_value
  relationship: none
  group_type: group
  admin_label: ''
  operator: '>'
  value:
    min: ''
    max: ''
    value: '+0 minutes'
    type: offset
  group: 1
  exposed: false
  expose:
    operator_id: ''
    label: ''
    description: ''
    use_operator: false
    operator: ''
    identifier: ''
    required: false
    remember: false
    multiple: false
    remember_roles:
      authenticated: authenticated
    placeholder: ''
    min_placeholder: ''
    max_placeholder: ''
  is_grouped: false
  group_info:
    label: ''
    description: ''
    identifier: ''
    optional: true
    widget: select
    multiple: false
    remember: false
    default_group: All
    default_group_multiple: {  }
    group_items: {  }
  plugin_id: datetime
