content:
  field_teaser_image:
    type: degov_preview_image
    weight: 0
    region: content
    label: hidden
    settings:
      view_mode: teaser_landscape_squared
      link: false
    third_party_settings: {  }
