"http://{default}/":
  type: upstream
  upstream: "app:http"
"http://www.{default}/":
  type: redirect
  to: "http://{default}/"
# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.
