file_delete_link:
  id: file_delete_link
  table: file_managed
  field: file_delete_link
  relationship: none
  group_type: group
  admin_label: ''
  label: Löschen
  exclude: true
  alter:
    alter_text: false
    text: ''
    make_link: false
    path: ''
    absolute: false
    external: false
    replace_spaces: false
    path_case: none
    trim_whitespace: false
    alt: ''
    rel: ''
    link_class: ''
    prefix: ''
    suffix: ''
    target: ''
    nl2br: false
    max_length: 0
    word_boundary: true
    ellipsis: true
    more_link: false
    more_link_text: ''
    more_link_path: ''
    strip_tags: false
    trim: false
    preserve_tags: ''
    html: false
  element_type: ''
  element_class: ''
  element_label_type: ''
  element_label_class: ''
  element_label_colon: true
  element_wrapper_type: ''
  element_wrapper_class: ''
  element_default_classes: true
  empty: ''
  hide_empty: false
  empty_zero: false
  hide_alter_empty: true
  text: Löschen
  entity_type: file
  plugin_id: degov_file_management_file_delete_link
dropbutton:
  id: dropbutton
  table: views
  field: dropbutton
  relationship: none
  group_type: group
  admin_label: ''
  label: Operations
  exclude: false
  alter:
    alter_text: false
    text: ''
    make_link: false
    path: ''
    absolute: false
    external: false
    replace_spaces: false
    path_case: none
    trim_whitespace: false
    alt: ''
    rel: ''
    link_class: ''
    prefix: ''
    suffix: ''
    target: ''
    nl2br: false
    max_length: 0
    word_boundary: true
    ellipsis: true
    more_link: false
    more_link_text: ''
    more_link_path: ''
    strip_tags: false
    trim: false
    preserve_tags: ''
    html: false
  element_type: ''
  element_class: ''
  element_label_type: ''
  element_label_class: ''
  element_label_colon: true
  element_wrapper_type: ''
  element_wrapper_class: ''
  element_default_classes: true
  empty: ''
  hide_empty: false
  empty_zero: false
  hide_alter_empty: true
  fields:
    file_delete_link: file_delete_link
    fid: '0'
    filename: '0'
    filemime: '0'
    filesize: '0'
    status: '0'
    created: '0'
    changed: '0'
    count: '0'
  destination: true
  plugin_id: dropbutton
