dependencies:
  config:
    - field.field.media.image.field_royalty_free
content:
  field_royalty_free:
    weight: 13
    settings:
      display_label: true
    third_party_settings: {  }
    type: boolean_checkbox
    region: content
  field_description:
    weight: 14
