uid:
  id: uid
  table: users_field_data
  field: uid
  relationship: uid
  group_type: group
  admin_label: ''
  operator: in
  value: {  }
  group: 1
  exposed: true
  expose:
    operator_id: uid_op
    label: Autor
    description: ''
    use_operator: false
    operator: uid_op
    identifier: uid
    required: false
    remember: false
    multiple: false
    remember_roles:
      authenticated: authenticated
      anonymous: '0'
      administrator: '0'
      manager: '0'
      editor: '0'
      usermanager: '0'
    reduce: false
  is_grouped: false
  group_info:
    label: ''
    description: ''
    identifier: ''
    optional: true
    widget: select
    multiple: false
    remember: false
    default_group: All
    default_group_multiple: {  }
    group_items: {  }
  entity_type: user
  entity_field: uid
  plugin_id: user_name
