degov_common.default_settings:
  type: config_object
  label: 'deGov - Common Settings'
  mapping:
    privacy_url:
      type: label
      label: 'Privacy URL Path'
    netiquette_url:
      type: label
      label: 'Netiquette URL Path'
    youtube_apikey:
      type: label
      label: 'Youtube API Key'

entity_browser.browser.selection_display.degov_multi_step_display:
  type: entity_browser.browser.selection_display.multi_step_display
