content:
  field_teaser_sub_title:
    type: string
    weight: 6
    region: content
    label: hidden
    settings:
      link_to_entity: false
    third_party_settings: {  }
  field_teaser_text:
    type: text_default
    weight: 7
    region: content
    label: hidden
    settings: {  }
    third_party_settings: {  }
  field_teaser_title:
    type: string
    weight: 5
    region: content
    label: hidden
    settings:
      link_to_entity: false
    third_party_settings: {  }
