display:
  default:
    display_options:
      query:
        type: views_query
        options:
          disable_sql_rewrite: true
          distinct: false
          replica: false
          query_comment: ''
          query_tags: {  }
